"""Validate the pinned dependency lock and critical provider compatibility."""

from pathlib import Path

def test_requirements_txt_is_pinned_lockfile():
    content = Path("requirements.txt").read_text(encoding="utf-8")
    assert "autogenerated by pip-compile" in content
    assert "pydantic-ai-slim==" in content
    assert any("==" in line and not line.startswith("#") for line in content.splitlines())


def test_requirements_in_is_human_editable_source():
    content = Path("requirements.in").read_text(encoding="utf-8")
    assert "pydantic-ai-slim[google]>=2.5,<3" in content
    assert "autogenerated" not in content


def test_pydantic_ai_google_provider_resolves():
    """Locked pydantic-ai stack must resolve the google: provider (not google-gla:)."""
    from pydantic_ai.models import infer_model

    from config.settings import pydantic_ai_gemini_model

    model_name = pydantic_ai_gemini_model()
    assert model_name.startswith("google:")
    assert "google-gla:" not in model_name

    model = infer_model(model_name)
    assert model is not None


def test_api_imports_with_locked_dependencies():
    import api.main  # noqa: F401

    assert api.main.app is not None
