#!/usr/bin/env bash
# Regenerate the Nginx Cloudflare snippets from Cloudflare's published edge IP
# ranges (https://www.cloudflare.com/ips-v4 and /ips-v6).
#
# Cloudflare adds/retires ranges occasionally; a stale list means either (a)
# real visitor IPs stop being restored (traffic from a new CF range logs as the
# CF node IP) or (b) legitimate CF nodes get 403'd by the origin lockdown. Run
# this on deploy and from a monthly cron, then reload Nginx.
#
# Regenerates:
#   ../nginx/snippets/cloudflare-realip.conf     (set_real_ip_from ...)
#   ../nginx/snippets/cloudflare-allowlist.conf  (geo $realip_remote_addr ...)
#
# Usage:
#   deploy/edge/cloudflare/update-cloudflare-ips.sh [--reload]
#     --reload   after writing, run `nginx -s reload` (or the containerised
#                equivalent) if Nginx is running.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SNIPPET_DIR="$(cd "${SCRIPT_DIR}/../nginx/snippets" && pwd)"
REALIP_FILE="${SNIPPET_DIR}/cloudflare-realip.conf"
ALLOWLIST_FILE="${SNIPPET_DIR}/cloudflare-allowlist.conf"

V4_URL="https://www.cloudflare.com/ips-v4"
V6_URL="https://www.cloudflare.com/ips-v6"

echo "→ Fetching Cloudflare IP ranges…"
V4="$(curl -fsS "$V4_URL")"
V6="$(curl -fsS "$V6_URL")"

if [[ -z "$V4" || -z "$V6" ]]; then
    echo "✗ Empty response from Cloudflare — refusing to overwrite snippets." >&2
    exit 1
fi

# --- cloudflare-realip.conf ------------------------------------------------
{
    echo "# Cloudflare real-IP restoration — GENERATED by update-cloudflare-ips.sh."
    echo "# Source: ${V4_URL} and ${V6_URL}"
    echo "# Included inside the http {} block."
    echo
    echo "# --- IPv4 ---"
    while IFS= read -r cidr; do
        [[ -n "$cidr" ]] && echo "set_real_ip_from ${cidr};"
    done <<< "$V4"
    echo
    echo "# --- IPv6 ---"
    while IFS= read -r cidr; do
        [[ -n "$cidr" ]] && echo "set_real_ip_from ${cidr};"
    done <<< "$V6"
    echo
    echo "real_ip_header    CF-Connecting-IP;"
    echo "real_ip_recursive on;"
} > "$REALIP_FILE"

# --- cloudflare-allowlist.conf ---------------------------------------------
{
    echo "# Cloudflare origin lockdown — GENERATED by update-cloudflare-ips.sh."
    echo "# Source: ${V4_URL} and ${V6_URL}"
    echo "# Included inside the http {} block. \$from_cloudflare = 1 only when the"
    echo "# DIRECT TCP peer (\$realip_remote_addr, before realip rewriting) is a"
    echo "# Cloudflare edge node or loopback."
    echo
    echo 'geo $realip_remote_addr $from_cloudflare {'
    echo "    default 0;"
    echo
    echo "    # Loopback — origin-local health checks / certbot self-tests."
    echo "    127.0.0.1/32 1;"
    echo "    ::1/128      1;"
    echo
    echo "    # --- Cloudflare IPv4 ---"
    while IFS= read -r cidr; do
        [[ -n "$cidr" ]] && echo "    ${cidr} 1;"
    done <<< "$V4"
    echo
    echo "    # --- Cloudflare IPv6 ---"
    while IFS= read -r cidr; do
        [[ -n "$cidr" ]] && echo "    ${cidr} 1;"
    done <<< "$V6"
    echo "}"
} > "$ALLOWLIST_FILE"

echo "✓ Wrote ${REALIP_FILE}"
echo "✓ Wrote ${ALLOWLIST_FILE}"

if [[ "${1:-}" == "--reload" ]]; then
    if command -v docker >/dev/null 2>&1 && docker ps --format '{{.Names}}' | grep -q '^ito-edge$'; then
        echo "→ Reloading Nginx in container ito-edge…"
        docker exec ito-edge nginx -t && docker exec ito-edge nginx -s reload
    elif command -v nginx >/dev/null 2>&1; then
        echo "→ Reloading host Nginx…"
        nginx -t && nginx -s reload
    else
        echo "! Nginx not found running — reload skipped. Reload manually to apply."
    fi
fi

echo "Done."
